//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Decisions_Project.CreativeWebDesign_dotNet_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CreativeWebDesigndotNetProject_dbEntities : DbContext
    {
        public CreativeWebDesigndotNetProject_dbEntities()
            : base("name=CreativeWebDesigndotNetProject_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<UserRecord> UserRecords { get; set; }
        public virtual DbSet<UserActivity> UserActivities { get; set; }
    }
}
