//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativeWebDesign_dotNet_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRecord
    {
        public UserRecord()
        {
            this.UserActivities = new HashSet<UserActivity>();
        }
    
        public string Id { get; set; }
        public Nullable<System.DateTime> TimeLoggedIn { get; set; }
        public Nullable<System.DateTime> TimeLoggedOff { get; set; }
        public string TimeOnMatrix { get; set; }
        public string TimeOnLandingPage { get; set; }
        public string UsersActivity { get; set; }
        public string Organization { get; set; }
        public string RoleInOrganization { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string StreetAddress { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Age { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string FinalChoice { get; set; }
    
        public virtual ICollection<UserActivity> UserActivities { get; set; }
    }
}
